{
  "openapi": "3.1.0",
  "info": {
    "title": "Impax Backend Swagger",
    "version": "0.1.0",
    "description": "Welcome to ImpaX, where innovation meets the field of sports, prioritizing the well-being of athletes. Our mission is to revolutionize athlete safety through cutting-edge impact monitoring technology.",
    "license": {
      "name": "MIT",
      "url": "https://github.com/cepdnaclk/e19-3yp-impact-tracker/blob/main/LICENSE"
    },
    "contact": {
      "name": "Impax",
      "url": "https://github.com/cepdnaclk/e19-3yp-impact-tracker",
      "email": ""
    }
  },
  "servers": [
    {
      "url": "http://localhost:5000"
    }
  ],
  "paths": {
    "/team": {
      "post": {
        "tags": ["TeamEndpoints"],
        "summary": "Create a team",
        "requestBody": {
          "$ref": "#/components/requestBodies/TeamCreateRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/Team"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },
    "/team/exists/teamId/{id}": {
      "get": {
        "tags": ["TeamEndpoints"],
        "summary": "Check if a team ID exists",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "exampleTeamId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TeamIdExistsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/team/{id}": {
      "get": {
        "tags": ["TeamEndpoints"],
        "summary": "Get team details",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "exampleTeamId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TeamResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },
    "/team/exists": {
      "get": {
        "tags": ["TeamEndpoints"],
        "summary": "Check if both Team ID and email exists",
        "parameters": [
          {
            "name": "teamId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "exampleTeamId"
          },
          {
            "name": "email",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "example@example.com"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TeamIdEmailExistsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/manager/exists/email/{email}": {
      "get": {
        "tags": ["ManagerEndpoints"],
        "summary": "Check if a manager email exists",
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "example@example.com"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/ManagerExistsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/manager": {
      "post": {
        "tags": ["ManagerEndpoints"],
        "summary": "Create a manager",
        "requestBody": {
          "$ref": "#/components/requestBodies/ManagerCreateRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/ManagerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },
    "/manager/{id}": {
      "get": {
        "tags": ["ManagerEndpoints"],
        "summary": "Get Manager Details",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "exampleManagerId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/ManagerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/player": {
      "post": {
        "tags": ["PlayerEndpoints"],
        "summary": "Create a player",
        "requestBody": {
          "$ref": "#/components/requestBodies/PlayerCreateRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/PlayerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },
    
    "/player/{email}": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get player details",
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "example@example.com"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/PlayerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/player/{playerID}/sessions": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get session details related to the player",
        "parameters": [
          {
            "name": "playerID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "examplePlayerId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/SessionDetailsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/players/{playerID}/total-impacts": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get total impacts for a player",
        "parameters": [
          {
            "name": "playerID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "examplePlayerId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TotalImpactsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/highest-impact": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get the highest impact among all records with the date",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/HighestImpactRecord"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },


    "/login/manager": {
      "post": {
        "tags": ["LoginEndpoints"],
        "summary": "Login as a manager",
        "requestBody": {
          "$ref": "#/components/requestBodies/LoginRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/login/player": {
      "post": {
        "tags": ["LoginEndpoints"],
        "summary": "Login as a player",
        "requestBody": {
          "$ref": "#/components/requestBodies/LoginRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    }



  },


  "components": {
    "schemas": {
      "LoginRequest": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          },
          "userName": {
            "type": "string"
          }
        },
        "example": {
          "password": "securePassword",
          "userName": "example@example.com"
        }
      },

      "ManagerExistsResponse": {
        "type": "object",
        "properties": {
          "managerExists": {
            "type": "boolean"
          }
        },
        "example": {
          "managerExists": true
        }
      },

      "ManagerCreateRequest": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "firstName": "John",
          "lastName": "Doe",
          "email": "john.doe@example.com",
          "password": "securePassword"
        }
      },

      "ManagerResponse": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "firstName": "John",
          "lastName": "Doe",
          "email": "john.doe@example.com"
        }
      },

      "TeamIdExistsResponse": {
        "type": "object",
        "properties": {
          "teamExists": {
            "type": "boolean"
          }
        },
        "example": {
          "teamExists": true
        }
      },
      "TeamManagerInterface": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "email": "example@example.com"
        }
      },
      "TeamIdEmailExistsResponse": {
        "type": "object",
        "properties": {
          "teamExists": {
            "type": "boolean"
          },
          "managerExists": {
            "type": "boolean"
          }
        },
        "example": {
          "teamExists": true,
          "managerExists": false
        }
      },

      "Team": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "teamName": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "teamName": "Example Team"
        }
      },
      
      "TeamResponse": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "teamName": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "teamName": "Example Team"
        }
      },      

      "PlayerCreateRequest": {
        "type": "object",
        "properties": {
          "playerId": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "teams": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "playerId": "examplePlayerId",
          "firstName": "John",
          "lastName": "Doe",
          "email": "example@example.com",
          "password": "securePassword",
          "address": "123 Main St",
          "teams": ["Team1", "Team2"]
        }
      },
      
      "PlayerResponse": {
        "type": "object",
        "properties": {
          "playerId": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "teams": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "playerId": "12345",
          "email": "example@example.com",
          "firstName": "John",
          "lastName": "Doe",
          "address": "123 Main St",
          "teams": ["Team1", "Team2"]
        }
      },
      
      "SessionDetailsResponse": {
        "type": "object",
        "properties": {
          "sessionId": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date"
          },
          "startTime": {
            "type": "string",
            "format": "time"
          },
          "endTime": {
            "type": "string",
            "format": "time"
          },
          "location": {
            "type": "string"
          },
          "hostManagerId": {
            "type": "string"
          },
          "players": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "sessionId": "12345",
          "date": "2023-01-01",
          "startTime": "10:00:00",
          "endTime": "12:00:00",
          "location": "Field 1",
          "hostManagerId": "host123",
          "players": ["player1", "player2"]
        }
      },
      
      "TotalImpactsResponse": {
        "type": "object",
        "properties": {
          "playerId": {
            "type": "string"
          },
          "totalImpacts": {
            "type": "integer"
          }
        },
        "example": {
          "playerId": "12345",
          "totalImpacts": 1000
        }
      },
      
      "HighestImpactRecord": {
        "type": "object",
        "properties": {
          "sessionId": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date"
          },
          "highestImpact": {
            "type": "number"
          }
        },
        "example": {
          "sessionId": "12345",
          "date": "2023-01-01",
          "highestImpact": 10.5
        }
      }
      
    },

    "requestBodies": {
      "TeamCreateRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Team"
            }
          }
        }
      },

      "PlayerCreateRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PlayerCreateRequest"
            }
          }
        }
      },

      "LoginRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/LoginRequest"
            }
          }
        }
      },

      "ManagerCreateRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ManagerCreateRequest"
            }
          }
        }
      },

      "TeamIdEmailCheckRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/TeamManagerInterface"
            }
          }
        }
      }
    }
  }
}

